---

galaxy_info:
  author: Wojtek Oledzki
  company: Voytek Solutions Ltd
  description: Build AWS Environment Foundation
  github_branch: master
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - development

dependencies:
  - role: sansible.users_and_groups
    users_and_groups:
      users:
        - name: "{{ example.name }}"

  - role: sansible.nginx

  - role: ansible-city.aws_bootstrap
